/**
 * The bash script the bundle runs: start `dsh` on a profile, open the URL it
 * prints, and stay in the foreground for as long as the server runs, so
 * whatever supervises the script stops the server by stopping it.
 */

import { CHROMIUM_BROWSER_IDS } from './applescript.ts'

/** Stands in for one `'` inside a single-quoted shell string: close, escape, reopen. */
const SHELL_QUOTE_ESCAPE = String.raw`'\''`

/**
 * The line `dsh web` prints once its Loader tree has settled and the server is
 * listening. It is the readiness signal, so a sibling that failed to load never
 * opens a tab on a dead app.
 */
export const URL_LINE_PREFIX = 'dsh web: '

/** Tenths of a second the launcher waits for that line before giving up. */
export const URL_WAIT_ATTEMPTS = 600

/**
 * Quote a value for safe interpolation into the generated shell launcher.
 * @param value - the raw string.
 * @returns the single-quoted form.
 */
export function shellQuote(value: string): string {
  return `'${value.replaceAll('\'', SHELL_QUOTE_ESCAPE)}'`
}

/** What the generated launcher needs baked into it. */
export interface LauncherOptions {
  /** Absolute path of the `dsh` launcher the app runs. */
  dsh: string
  /** Profile it boots: `dsh --profile <name>`. */
  profile: string
  /** Arguments appended after the profile, verbatim — the web app's own flags. */
  webArgs: readonly string[]
  /** Directories of the `PATH` the app runs under; a Finder launch inherits none. */
  path: readonly string[]
  /** `DSH_HOME` to export, when the build was told to pin one. */
  dshHome?: string | undefined
  /** Bundle name, which names the log directory and titles the failure alert. */
  appName: string
}

/**
 * Build the launch script.
 *
 * Finder launches inherit neither the login shell's `PATH` nor its working
 * directory, so `PATH` is exported here and the launcher moves to the home
 * directory before starting. Bash 3.2 is the system shell — the script stays
 * within it, which is why the argument array is expanded the long way.
 * @param options - the values to bake in.
 * @returns the launcher script.
 */
export function launcherScript(options: LauncherOptions): string {
  const webArgs = options.webArgs.map(shellQuote).join(' ')
  const dshHome = options.dshHome === undefined
    ? ''
    : `# Pinned at build time: a Finder launch sees no shell environment.\nDSH_HOME=${shellQuote(options.dshHome)}\nexport DSH_HOME\n`
  return `#!/bin/bash
# Generated by @wanghao9610/omdsh-webapp — edits are overwritten.
set -uo pipefail

DSH=${shellQuote(options.dsh)}
PROFILE=${shellQuote(options.profile)}
APP=${shellQuote(options.appName)}
WEB_ARGS=(${webArgs})
PATH=${shellQuote(options.path.join(':'))}
export PATH
${dshHome}
LOG_DIR="$HOME/Library/Logs/$APP"
LOG="$LOG_DIR/web.log"
# Where the run that owns the port records its URL, written only once a tab
# shows it. The port answers more than a second before that tab exists, and an
# activation landing inside that interval would find none and open a second one.
SERVING="$LOG_DIR/serving-url"

alert() {
  /usr/bin/osascript -e "display alert \\"$APP\\" message \\"$1\\" as critical" >/dev/null 2>&1 || true
}

# Resolved from this script's own location, so the bundle stays movable: the
# path holds in both layouts, whether the script sits in Resources beside the
# helpers or in MacOS as the executable itself.
RESOURCES="$(cd "$(dirname "$0")/../Resources" && pwd)"
CHROMIUM_BROWSER_IDS=(${CHROMIUM_BROWSER_IDS.map(shellQuote).join(' ')})

# Raise the tab already showing the app instead of stacking up new ones. Only
# browsers that are already running are asked, so this never starts one, and an
# unmatched URL falls through to a fresh tab in the default browser.
focus_or_open() {
  local target="$1"
  local browser
  for browser in "\${CHROMIUM_BROWSER_IDS[@]}"; do
    if /usr/bin/osascript "$RESOURCES/focus-chromium.applescript" "$browser" "$target" 2>/dev/null | /usr/bin/grep -q '^focused$'; then
      return 0
    fi
  done
  if /usr/bin/osascript "$RESOURCES/focus-safari.applescript" "$target" 2>/dev/null | /usr/bin/grep -q '^focused$'; then
    return 0
  fi
  /usr/bin/open "$target"
}

# Print the URL a live server is answering on, if there is one. A killed run
# leaves its marker behind, so the probe — not the marker — is what decides.
serving_url() {
  local url
  [ -f "$SERVING" ] || return 1
  read -r url < "$SERVING" || return 1
  [ -n "$url" ] || return 1
  /usr/bin/curl -fsS --max-time 1 -o /dev/null "$url" || return 1
  printf '%s' "$url"
}

# The executable runs this mode whenever the user reaches the app, which is also
# why it starts nothing: an activation arrives moments after launch, and
# starting a server here would race the launch below for the port.
if [ "\${1:-}" = "focus" ]; then
  if url=$(serving_url); then focus_or_open "$url"; fi
  exit 0
fi

mkdir -p "$LOG_DIR"
cd "$HOME" || exit 1

# An instance already serving owns the port; this run is only here to surface it.
if url=$(serving_url); then
  focus_or_open "$url"
  exit 0
fi

if [ ! -x "$DSH" ]; then
  alert "No dsh launcher at $DSH. Reinstall the harness CLI, then rebuild this app with 'pnpm run package:mac'."
  exit 1
fi

: > "$LOG"
rm -f "$SERVING"
# Bash 3.2 counts an empty array as unset under 'set -u', so it is expanded the
# long way rather than as "\${WEB_ARGS[@]}".
"$DSH" --profile "$PROFILE" \${WEB_ARGS[@]+"\${WEB_ARGS[@]}"} >>"$LOG" 2>&1 &
child=$!
# The marker goes first: stopping the server can take long enough for the app's
# own exit to cut this handler short, and a marker left over a dead URL is one
# more probe on the next launch.
trap 'rm -f "$SERVING"; kill "$child" 2>/dev/null; wait "$child" 2>/dev/null; exit 0' TERM INT

url=""
attempt=0
while [ "$attempt" -lt ${String(URL_WAIT_ATTEMPTS)} ]; do
  if ! kill -0 "$child" 2>/dev/null; then break; fi
  line=$(/usr/bin/grep -m1 -o ${shellQuote(`${URL_LINE_PREFIX}[^ ]*`)} "$LOG" 2>/dev/null)
  if [ -n "$line" ]; then url="\${line#${URL_LINE_PREFIX}}"; break; fi
  sleep 0.1
  attempt=$((attempt + 1))
done

if [ -z "$url" ]; then
  # Still running but never said it was serving: nothing is going to use it.
  kill "$child" 2>/dev/null
  wait "$child" 2>/dev/null
  # A profile that could not take its port is usually losing it to a session
  # already serving — a dsh started from a terminal, or a copy of this app
  # under another home. Reaching that session is what the launch asked for.
  # Only a port held by something that answers nothing is a failure.
  taken=$(/usr/bin/grep -m1 -o 'EADDRINUSE: address already in use [^ ]*' "$LOG" 2>/dev/null)
  if [ -n "$taken" ]; then
    address="\${taken##* }"
    host="\${address%:*}"
    port="\${address##*:}"
    case "$host" in
      0.0.0.0|::|'[::]') host=127.0.0.1 ;;
      *:*) host="[$host]" ;;
    esac
    existing="http://$host:$port"
    if /usr/bin/curl -fsS --max-time 2 -o /dev/null "$existing"; then
      focus_or_open "$existing"
      exit 0
    fi
    alert "Port $port is held by something that is not serving. Stop it, or rebuild this app on another port. See $LOG"
    exit 1
  fi
  alert "The $PROFILE profile did not start serving. See $LOG"
  exit 1
fi

focus_or_open "$url"
# Only now is there a tab for an activation to raise.
printf '%s\\n' "$url" > "$SERVING"
wait "$child"
`
}
