/** The C# source compiled into the native Windows launcher. */

/** What the generated launcher needs baked into it. */
export interface WindowsLauncherOptions {
  /** Application and tray name. */
  appName: string
  /** Package version embedded in the executable metadata. */
  version: string
  /** Hash safe for mutex and named-pipe names. */
  instanceKey: string
  /** Absolute `dsh`, `dsh.cmd`, or `dsh.exe` path. */
  dsh: string
  /** Profile it boots. */
  profile: string
  /** Arguments passed to the profile application. */
  webArgs: readonly string[]
  /** Search path used by the harness process. */
  path: readonly string[]
  /** Optional pinned harness home. */
  dshHome?: string | undefined
  /** Optional Edge or Chrome executable override. */
  browser?: string | undefined
}

/** Quote one TypeScript value as a C# string literal. */
export function csharpString(value: string): string {
  return JSON.stringify(value)
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029')
}

/** Turn a semver-like package version into four numeric assembly components. */
export function windowsAssemblyVersion(version: string): string {
  const numbers = version.match(/\d+/g)?.slice(0, 4).map((part) => Math.min(Number(part), 65_534)) ?? []
  while (numbers.length < 4) numbers.push(0)
  return numbers.join('.')
}

/** Quote a literal for the Windows PowerShell command that invokes `dsh`. */
export function powershellQuote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

/**
 * Encode the small PowerShell bridge used to invoke `.cmd`, `.bat`, or native
 * launchers without interpolating profile arguments into a `cmd.exe` string.
 */
export function windowsPowerShellCommand(options: Pick<WindowsLauncherOptions, 'dsh' | 'profile' | 'webArgs'>): string {
  const argumentsSource = [options.dsh, '--profile', options.profile, ...options.webArgs]
    .map(powershellQuote)
    .join(' ')
  const source = `& ${argumentsSource}\nif ($LASTEXITCODE -is [int]) { exit $LASTEXITCODE }\nif (-not $?) { exit 1 }\n`
  return Buffer.from(source, 'utf16le').toString('base64')
}

/**
 * Build C# 5 source so the .NET Framework compiler included with Windows can
 * produce the launcher without an SDK or package restore.
 */
export function windowsLauncherSource(options: WindowsLauncherOptions): string {
  const argumentsSource = options.webArgs.map(csharpString).join(', ')
  const dshHome = options.dshHome === undefined ? 'null' : csharpString(options.dshHome)
  const browser = options.browser === undefined ? 'null' : csharpString(options.browser)
  return `// Generated by @omdsh-plugins/omdsh-webapp — edits are overwritten.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.IO.Pipes;
using System.Net;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows.Forms;

[assembly: System.Reflection.AssemblyTitle(${csharpString(options.appName)})]
[assembly: System.Reflection.AssemblyProduct(${csharpString(options.appName)})]
[assembly: System.Reflection.AssemblyVersion(${csharpString(windowsAssemblyVersion(options.version))})]
[assembly: System.Reflection.AssemblyFileVersion(${csharpString(windowsAssemblyVersion(options.version))})]

internal static class Settings
{
    internal const string AppName = ${csharpString(options.appName)};
    internal const string InstanceKey = ${csharpString(options.instanceKey)};
    internal const string Dsh = ${csharpString(options.dsh)};
    internal const string Profile = ${csharpString(options.profile)};
    internal const string SearchPath = ${csharpString(options.path.join(';'))};
    internal static readonly string DshHome = ${dshHome};
    internal static readonly string Browser = ${browser};
    internal const string PowerShellCommand = ${csharpString(windowsPowerShellCommand(options))};
    internal static readonly string[] WebArgs = new string[] { ${argumentsSource} };
}

internal static class Program
{
    [STAThread]
    private static void Main(string[] args)
    {
        string request = args.Length > 0 && args[0] == "--quit" ? "quit" : "activate";
        bool ownsInstance;
        using (var mutex = new Mutex(true, @"Local\\omdsh-webapp-" + Settings.InstanceKey, out ownsInstance))
        {
            if (!ownsInstance)
            {
                ActivateExisting(request);
                return;
            }
            if (request == "quit") return;
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            using (var context = new LauncherContext())
            {
                Application.Run(context);
            }
            GC.KeepAlive(mutex);
        }
    }

    private static void ActivateExisting(string request)
    {
        for (int attempt = 0; attempt < 10; attempt++)
        {
            try
            {
                using (var client = new NamedPipeClientStream(".", "omdsh-webapp-" + Settings.InstanceKey, PipeDirection.Out))
                {
                    client.Connect(250);
                    using (var writer = new StreamWriter(client))
                    {
                        writer.AutoFlush = true;
                        writer.WriteLine(request);
                    }
                    return;
                }
            }
            catch (TimeoutException) { Thread.Sleep(100); }
            catch (IOException) { Thread.Sleep(100); }
        }
        MessageBox.Show("The existing instance did not answer. End it in Task Manager, then try again.",
            Settings.AppName, MessageBoxButtons.OK, MessageBoxIcon.Error);
    }
}

internal sealed class LauncherContext : ApplicationContext
{
    private const string UrlPrefix = "dsh web: ";
    private readonly Control dispatcher;
    private readonly NotifyIcon tray;
    private readonly string logDirectory;
    private readonly string logPath;
    private readonly object logLock = new object();
    private Thread pipeThread;
    private Process child;
    private IntPtr browserWindow = IntPtr.Zero;
    private bool browserStarting;
    private volatile bool closing;
    private string servingUrl;

    internal LauncherContext()
    {
        logDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), Settings.AppName, "Logs");
        logPath = Path.Combine(logDirectory, "web.log");
        Directory.CreateDirectory(logDirectory);

        dispatcher = new Control();
        IntPtr ignored = dispatcher.Handle;
        var menu = new ContextMenuStrip();
        menu.Items.Add("Open", null, delegate { ShowSession(); });
        menu.Items.Add("View log", null, delegate { OpenLog(); });
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add("Exit", null, delegate { ExitApplication(); });
        Icon icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath) ?? SystemIcons.Application;
        tray = new NotifyIcon();
        tray.Icon = icon;
        tray.Text = Settings.AppName.Length > 63 ? Settings.AppName.Substring(0, 63) : Settings.AppName;
        tray.ContextMenuStrip = menu;
        tray.DoubleClick += delegate { ShowSession(); };
        tray.Visible = true;

        pipeThread = new Thread(ListenForActivation);
        pipeThread.IsBackground = true;
        pipeThread.Name = "activation-pipe";
        pipeThread.Start();
        var serverThread = new Thread(StartServer);
        serverThread.IsBackground = true;
        serverThread.Name = "dsh-server";
        serverThread.Start();
    }

    private void ListenForActivation()
    {
        while (!closing)
        {
            try
            {
                using (var server = new NamedPipeServerStream("omdsh-webapp-" + Settings.InstanceKey, PipeDirection.In, 1))
                {
                    server.WaitForConnection();
                    if (closing) return;
                    using (var reader = new StreamReader(server))
                    {
                        string request = reader.ReadLine();
                        if (request == "quit") Post(ExitApplication);
                        else if (request == "activate") Post(ShowSession);
                    }
                }
            }
            catch (IOException) { if (!closing) Thread.Sleep(100); }
            catch (ObjectDisposedException) { return; }
        }
    }

    private void StartServer()
    {
        try
        {
            if (!File.Exists(Settings.Dsh))
            {
                Fail("No dsh launcher at " + Settings.Dsh + ". Reinstall the harness CLI, then rebuild this app with 'pnpm run package:win'.");
                return;
            }
            lock (logLock) File.WriteAllText(logPath, String.Empty, new UTF8Encoding(false));
            var ready = new ManualResetEvent(false);
            var output = new StringBuilder();
            var start = CreateDshStartInfo();
            child = new Process();
            child.StartInfo = start;
            child.EnableRaisingEvents = true;
            DataReceivedEventHandler receive = delegate(object sender, DataReceivedEventArgs args)
            {
                if (args.Data == null) return;
                AppendLog(args.Data);
                lock (output) output.AppendLine(args.Data);
                if (args.Data.StartsWith(UrlPrefix, StringComparison.Ordinal))
                {
                    string candidate = args.Data.Substring(UrlPrefix.Length).Trim();
                    if (candidate.Length > 0)
                    {
                        servingUrl = candidate;
                        ready.Set();
                    }
                }
            };
            child.OutputDataReceived += receive;
            child.ErrorDataReceived += receive;
            child.Exited += delegate { ready.Set(); };
            if (!child.Start())
            {
                Fail("The harness process could not be started.");
                return;
            }
            child.BeginOutputReadLine();
            child.BeginErrorReadLine();

            if (!ready.WaitOne(TimeSpan.FromSeconds(60)) || String.IsNullOrEmpty(servingUrl))
            {
                string captured;
                lock (output) captured = output.ToString();
                string existing = ExistingSessionUrl(captured);
                if (existing != null && Probe(existing, 2000))
                {
                    StopChild();
                    OpenDefaultBrowser(existing);
                    Post(ExitThread);
                    return;
                }
                StopChild();
                if (existing != null)
                    Fail("Port " + new Uri(existing).Port + " is held by something that is not serving. Stop it, or rebuild this app on another port. See " + logPath);
                else
                    Fail("The " + Settings.Profile + " profile did not start serving. See " + logPath);
                return;
            }

            Post(ShowSession);
            child.WaitForExit();
            if (!closing) Fail("The harness server stopped. See " + logPath);
        }
        catch (Exception error)
        {
            AppendLog(error.ToString());
            Fail("The application could not start. See " + logPath);
        }
    }

    private static ProcessStartInfo CreateDshStartInfo()
    {
        string system = Environment.GetFolderPath(Environment.SpecialFolder.System);
        string powershell = Path.Combine(system, "WindowsPowerShell", "v1.0", "powershell.exe");
        var info = new ProcessStartInfo(powershell,
            "-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand " + Settings.PowerShellCommand);
        info.UseShellExecute = false;
        info.CreateNoWindow = true;
        info.RedirectStandardOutput = true;
        info.RedirectStandardError = true;
        info.WorkingDirectory = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        info.EnvironmentVariables["PATH"] = Settings.SearchPath;
        if (Settings.DshHome != null) info.EnvironmentVariables["DSH_HOME"] = Settings.DshHome;
        return info;
    }

    private static string QuoteArgument(string value)
    {
        if (value.Length > 0 && value.IndexOfAny(new char[] { ' ', '\\t', '\\r', '\\n', '\"' }) < 0) return value;
        var result = new StringBuilder("\\\"");
        int slashes = 0;
        foreach (char character in value)
        {
            if (character == '\\\\') { slashes++; continue; }
            if (character == '\"') result.Append('\\\\', slashes * 2 + 1);
            else result.Append('\\\\', slashes);
            result.Append(character);
            slashes = 0;
        }
        result.Append('\\\\', slashes * 2);
        result.Append('\"');
        return result.ToString();
    }

    private static string ExistingSessionUrl(string output)
    {
        Match match = Regex.Match(output, @"EADDRINUSE: address already in use (?<address>[^\\s]+)");
        if (!match.Success) return null;
        string address = match.Groups["address"].Value;
        int separator = address.LastIndexOf(':');
        if (separator < 0) return null;
        int port;
        if (!Int32.TryParse(address.Substring(separator + 1), out port)) return null;
        string host = address.Substring(0, separator).Trim('[', ']');
        if (host == "0.0.0.0" || host == "::" || host.Length == 0) host = "127.0.0.1";
        else if (host.IndexOf(':') >= 0) host = "[" + host + "]";
        return "http://" + host + ":" + port;
    }

    private static bool Probe(string url, int timeout)
    {
        try
        {
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "GET";
            request.Timeout = timeout;
            request.AllowAutoRedirect = true;
            using (var response = (HttpWebResponse)request.GetResponse()) return (int)response.StatusCode < 500;
        }
        catch (WebException error)
        {
            var response = error.Response as HttpWebResponse;
            if (response == null) return false;
            using (response) return (int)response.StatusCode < 500;
        }
    }

    private void ShowSession()
    {
        if (closing) return;
        if (String.IsNullOrEmpty(servingUrl))
        {
            tray.ShowBalloonTip(1500, Settings.AppName, "The harness is still starting.", ToolTipIcon.Info);
            return;
        }
        if (browserWindow != IntPtr.Zero && NativeMethods.IsWindow(browserWindow))
        {
            NativeMethods.ShowWindow(browserWindow, NativeMethods.SW_RESTORE);
            NativeMethods.SetForegroundWindow(browserWindow);
            return;
        }
        if (browserStarting) return;
        browserStarting = true;
        string url = servingUrl;
        var thread = new Thread(delegate()
        {
            IntPtr window = StartAppBrowser(url);
            Post(delegate
            {
                browserStarting = false;
                browserWindow = window;
            });
        });
        thread.IsBackground = true;
        thread.Start();
    }

    private static IntPtr StartAppBrowser(string url)
    {
        string browser = FindBrowser();
        if (browser == null)
        {
            OpenDefaultBrowser(url);
            return IntPtr.Zero;
        }
        string processName = Path.GetFileNameWithoutExtension(browser);
        var before = WindowHandlesFor(processName);
        try
        {
            Process.Start(new ProcessStartInfo(browser, "--app=" + QuoteArgument(url)) { UseShellExecute = false });
            for (int attempt = 0; attempt < 100; attempt++)
            {
                Thread.Sleep(100);
                foreach (IntPtr handle in WindowHandlesFor(processName))
                {
                    if (!before.Contains(handle))
                    {
                        NativeMethods.SetForegroundWindow(handle);
                        return handle;
                    }
                }
            }
        }
        catch { OpenDefaultBrowser(url); }
        return IntPtr.Zero;
    }

    private static HashSet<IntPtr> WindowHandlesFor(string processName)
    {
        var processIds = new HashSet<uint>();
        foreach (Process process in Process.GetProcessesByName(processName))
        {
            try { processIds.Add((uint)process.Id); }
            finally { process.Dispose(); }
        }
        var handles = new HashSet<IntPtr>();
        NativeMethods.EnumWindows(delegate(IntPtr handle, IntPtr parameter)
        {
            uint processId;
            NativeMethods.GetWindowThreadProcessId(handle, out processId);
            if (processIds.Contains(processId) && NativeMethods.IsWindowVisible(handle)) handles.Add(handle);
            return true;
        }, IntPtr.Zero);
        return handles;
    }

    private static string FindBrowser()
    {
        if (!String.IsNullOrEmpty(Settings.Browser) && File.Exists(Settings.Browser)) return Settings.Browser;
        string programFiles = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles);
        string programFilesX86 = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86);
        string local = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        string[] candidates = new string[] {
            Path.Combine(programFilesX86, "Microsoft", "Edge", "Application", "msedge.exe"),
            Path.Combine(programFiles, "Microsoft", "Edge", "Application", "msedge.exe"),
            Path.Combine(programFiles, "Google", "Chrome", "Application", "chrome.exe"),
            Path.Combine(local, "Google", "Chrome", "Application", "chrome.exe")
        };
        foreach (string candidate in candidates) if (File.Exists(candidate)) return candidate;
        return null;
    }

    private static void OpenDefaultBrowser(string url)
    {
        try { Process.Start(new ProcessStartInfo(url) { UseShellExecute = true }); }
        catch { }
    }

    private void OpenLog()
    {
        try { Process.Start(new ProcessStartInfo(logPath) { UseShellExecute = true }); }
        catch (Exception error) { MessageBox.Show(error.Message, Settings.AppName, MessageBoxButtons.OK, MessageBoxIcon.Error); }
    }

    private void AppendLog(string line)
    {
        lock (logLock) File.AppendAllText(logPath, line + Environment.NewLine, new UTF8Encoding(false));
    }

    private void Fail(string message)
    {
        Post(delegate
        {
            if (!closing) MessageBox.Show(message, Settings.AppName, MessageBoxButtons.OK, MessageBoxIcon.Error);
            ExitApplication();
        });
    }

    private void Post(Action action)
    {
        if (dispatcher.IsDisposed) return;
        try { dispatcher.BeginInvoke(action); }
        catch (InvalidOperationException) { }
    }

    private void ExitApplication()
    {
        if (closing) return;
        closing = true;
        tray.Visible = false;
        if (browserWindow != IntPtr.Zero && NativeMethods.IsWindow(browserWindow))
            NativeMethods.PostMessage(browserWindow, NativeMethods.WM_CLOSE, IntPtr.Zero, IntPtr.Zero);
        StopChild();
        ExitThread();
    }

    private void StopChild()
    {
        Process process = child;
        if (process == null) return;
        try
        {
            if (!process.HasExited)
            {
                Process killer = Process.Start(new ProcessStartInfo("taskkill.exe", "/PID " + process.Id + " /T /F")
                {
                    UseShellExecute = false,
                    CreateNoWindow = true
                });
                if (killer != null) killer.WaitForExit(5000);
            }
        }
        catch { try { if (!process.HasExited) process.Kill(); } catch { } }
    }

    protected override void ExitThreadCore()
    {
        closing = true;
        tray.Visible = false;
        base.ExitThreadCore();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            tray.Dispose();
            dispatcher.Dispose();
            if (child != null) child.Dispose();
        }
        base.Dispose(disposing);
    }
}

internal static class NativeMethods
{
    internal const int SW_RESTORE = 9;
    internal const int WM_CLOSE = 0x0010;
    internal delegate bool EnumWindowsProc(IntPtr window, IntPtr parameter);

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static extern bool EnumWindows(EnumWindowsProc callback, IntPtr parameter);

    [DllImport("user32.dll")]
    internal static extern uint GetWindowThreadProcessId(IntPtr window, out uint processId);

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static extern bool IsWindowVisible(IntPtr window);

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static extern bool IsWindow(IntPtr window);

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static extern bool ShowWindow(IntPtr window, int command);

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static extern bool SetForegroundWindow(IntPtr window);

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static extern bool PostMessage(IntPtr window, int message, IntPtr wParam, IntPtr lParam);
}
`
}
